### ISSUE TITLE
Have an option to disable SSOWAT user panel

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/redirect_ynh#3]
It would be nice to have an option to disable the SSOWAT resource fetcher : 

```
  # Include SSOWAT user panel.
  include conf.d/yunohost_panel.conf.inc;
```

I don't quite get how this is actually supposed to work, unless the redirected host is serving  yunohost too...

**Comment by scith** [comment]
Hi,
I think that this is crucial because the SSOWAT has 2 functions:
- Protect access (in case you are using redirect_ynh to serve a local content that needs to be protected from the outside world.)
- Add the YunoHost tile overlay, which helps for the unified experience of YunoHost

Note that the SSOWAT is automatically disabled in case of a public redirect (is_public is true). So if you set your redirect to public this is disabled

Cheers
